from tkinter import PhotoImage

copy = PhotoImage(file='images/copy.png')
cut = PhotoImage(file='images/cut.png')
delete = PhotoImage(file='images/delete.png')
desktop = PhotoImage(file='images/desktop.png')
documents = PhotoImage(file='images/documents.png')
downloads = PhotoImage(file='images/downloads.png')
file = PhotoImage(file='images/file.png')
folder = PhotoImage(file='images/folder.png')
gallery = PhotoImage(file='images/gallery.png')
home = PhotoImage(file='images/home.png')
music = PhotoImage(file='images/music.png')
new_folder = PhotoImage(file='images/newf.png')
paste = PhotoImage(file='images/paste.png')
rename = PhotoImage(file='images/rename.png')
videos = PhotoImage(file='images/video.png')
